[package]
name = "org_element"
version = "1.0.0"
authors = ["Org-rs maintainers"]
edition = "2018"
license = "GPL-3.0-or-later"


[dependencies]
memchr = "2.0"
regex = "1"
lazy_static = "^1.3.0"
bumpalo = { version = "3", features = ["collections"] }

[dev-dependencies]
criterion = "0.5"
lexpr = "0.2"
goof = "0.3"

[lib]
name = "org_element"

[[bench]]
name = "parse"
path = "benches/parse.rs"
harness = false

[[bench]]
name = "pattern"
path = "benches/pattern.rs"
harness = false
